services:
  - type: web
    name: eco-opti-agent
    env: python
    plan: free
    buildCommand: "pip install -r backened/requirement.txt"
    startCommand: "cd backened && gunicorn main:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GOOGLE_API_KEY
        sync: false
